# Setup
title:               Jayden Qi's Blog
tagline:             ''
description:         'A blog about my musings, projects, and code'
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Jayden Q
  email:             jaydeniqv2@gmail.com
  discord:           jayandjeff

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
